---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: unifi-mcp
  namespace: ai
spec:
  image: ghcr.io/sirkirby/unifi-network-mcp:0.32.10@sha256:900ae8a02c9edc35e3d8c2bcb5416657fd9752a632d4802ea8e121eac14ea187
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 3000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  secrets:
    - name: unifi-mcp-secret
      key: UNIFI_API_KEY
      targetEnvName: UNIFI_API_KEY
  env:
    - name: UNIFI_MCP_HTTP_ENABLED
      value: "true"
    - name: UNIFI_HOST
      value: https://192.168.1.1
    - name: UNIFI_VERIFY_SSL
      value: "false"
  groupRef:
    name: mcp-tools
