---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: line
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: line-secret
    template:
      data:
        INIT_POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_USER: "{{ .LINE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LINE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_DBNAME: line
        DATABASE_URL: "postgres://{{ .LINE_POSTGRES_USER }}:{{ .LINE_POSTGRES_PASSWORD }}@postgres-rw.storage.svc.cluster.local:5432/line?sslmode=disable"
        S3_ACCESS_KEY: "{{ .GARAGE_ROOT_USER }}"
        S3_SECRET_KEY: "{{ .GARAGE_ROOT_PASSWORD }}"
        VAPID_PUBLIC_KEY: "{{ .LINE_VAPID_PUBLIC_KEY }}"
        VAPID_PRIVATE_KEY: "{{ .LINE_VAPID_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: line
    - extract:
        key: cloudnative-pg
    - extract:
        key: garage
