---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-workflows
      version: 1.0.13
      sourceRef:
        kind: HelmRepository
        name: argo-workflows
  values:
    server:
      enabled: true
    controller:
      workflowNamespaces:
        - kubeflow
      extraEnv:
        - name: WATCH_CONTROLLER_SEMAPHORE_CONFIGMAPS
          value: "false"
      podAnnotations:
        reloader.stakater.com/auto: "true"
    useDefaultArtifactRepo: true
    executor:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL
    workflowDefaults:
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
