---
configs:
  poll-config.yml:
    content: |
      - run_once: false
        interval: 180s
        url: https://github.com/solanyn/home-ops.git
        reference: main
secrets:
  connect_token:
    file: /mnt/world/doco-cd/1password-connect/connect-token
  webhook_secret:
    file: /mnt/world/doco-cd/webhook_secret
services:
  op-connect-api:
    image: ghcr.io/1password/connect-api:1.8.2@sha256:fabf0a353791f7d70851767c6d58595eb386a86ba4ada4a8ca41b3668a096b5d
    environment:
      OP_HTTP_PORT: 8080
      OP_SESSION: /home/opuser/.op/1password-credentials.json
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:8080/heartbeat]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - /mnt/world/doco-cd/1password-connect/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro
      - /mnt/world/doco-cd/1password-connect/data:/home/opuser/.op/data

  op-connect-sync:
    image: ghcr.io/1password/connect-sync:1.8.2@sha256:3844a6410e119ccec72011737d5b46afe4be12cb0f54f681fe3ce999280449d8
    environment:
      OP_HTTP_PORT: 8081
      OP_SESSION: /home/opuser/.op/1password-credentials.json
    depends_on:
      op-connect-api:
        condition: service_healthy
    volumes:
      - /mnt/world/doco-cd/1password-connect/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro
      - /mnt/world/doco-cd/1password-connect/data:/home/opuser/.op/data

  app:
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    container_name: doco-cd
    depends_on:
      op-connect-api:
        condition: service_healthy
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
      HTTP_PORT: 8080
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_CONNECT_HOST: http://op-connect-api:8080
      SECRET_PROVIDER_CONNECT_TOKEN_FILE: /run/secrets/connect_token
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
    healthcheck:
      test: [CMD, /doco-cd, healthcheck]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.117.1@sha256:9db114c98e4fffa2f88a5ded0d4f71356334310057398f31105cabb004077e28
    ports:
      - 8080:8080
      - 9120:9120
    restart: unless-stopped
    secrets:
      - connect_token
      - webhook_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/world/doco-cd:/data
volumes: {}
