---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: garage-operator
spec:
    interval: 1h
    path: ./kubernetes/apps/storage/garage-operator/app
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    targetNamespace: garage-operator-system
    dependsOn:
        - name: namespace
          namespace: flux-system
    postBuild:
        substitute:
            APP: garage-operator
    wait: false
