---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-webhook-flux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-webhook-flux-secret
    template:
      data:
        token: "{{ .FLUX_WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        key: openclaw-webhook
