---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-ops-actions-cache-server
spec:
  chartRef:
    kind: OCIRepository
    name: home-ops-actions-cache-server
  interval: 1h
  values:
    defaultPodOptions:
      enableServiceLinks: false
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/falcondev-oss/github-actions-cache-server
              tag: 9.4.3@sha256:fdc457c9dfcecf0ad2cfb11511327c74d6d654a7d2489023afdf1f7334d62628
            env:
              API_BASE_URL: http://home-ops-actions-cache-server.actions-runner-system.svc.cluster.local:3000
              STORAGE_DRIVER: filesystem
              STORAGE_FILESYSTEM_PATH: /data/cache
              DB_DRIVER: sqlite
              DB_SQLITE_PATH: /data/cache-server.db
              CLEANUP_OLDER_THAN_DAYS: "7"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: 3000
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /data
