---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pkvault
spec:
  chartRef:
    kind: OCIRepository
    name: pkvault
  interval: 10m
  timeout: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      pkvault:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/chnapy/pkvault
              tag: 2.3.2@sha256:1c1605c792b699257789da09a23bb0ca54c8ab1f3cb8629b5357755b623fe572
            env:
              TZ: Australia/Sydney
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 3000
                  initialDelaySeconds: 20
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 20
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 5
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - pkvault.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /pkvault
