---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
    name: label-studio
spec:
    clusterRef:
        name: garage
    globalAlias: label-studio
    bucketId: 52c8dcc9e81e4438d520806de9637f672f325ce89670745b1ff1127de80bf6df
