---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speakr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: speakr-secret
    template:
      data:
        TEXT_MODEL_BASE_URL: https://gateway.goyangi.io/v1/opus
        TEXT_MODEL_API_KEY: "{{ .AGENTGATEWAY_PERSONAL_API_KEY }}"
        TEXT_MODEL_NAME: opus
        SECRET_KEY: "{{ .SPEAKR_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: agentgateway
    - extract:
        key: speakr
