---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
    name: bronze
spec:
    clusterRef:
        name: garage
    globalAlias: bronze
    bucketId: 33a77e196c9d8cc95577ac2b3c4118d124244672cf8863dc4efa71c5956bbecc
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
    name: silver
spec:
    clusterRef:
        name: garage
    globalAlias: silver
    bucketId: 2702a200b4f79b91d995566fff176067d5f23a36e5b5f51c189c803f02ad0e49
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
    name: gold
spec:
    clusterRef:
        name: garage
    globalAlias: gold
    bucketId: c5edb9f41c5720afcaa6126ac37d536eaf672d6618f811cfae2201ca2592a96b
