---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: garage-nas
spec:
  endpoints:
    - dnsName: s3.goyangi.io
      recordType: A
      targets:
        - 192.168.42.9
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: garage-admin.goyangi.io
      recordType: A
      targets:
        - 192.168.42.9
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: s3-versitygw.goyangi.io
      recordType: A
      targets:
        - 192.168.42.9
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: versitygw-admin.goyangi.io
      recordType: A
      targets:
        - 192.168.42.9
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: versitygw.goyangi.io
      recordType: A
      targets:
        - 192.168.42.9
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
