---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: victoria-operator-crds
spec:
    targetNamespace: o11y
    path: ./kubernetes/apps/o11y/victoria/crds
    prune: false
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    interval: 1h
    retryInterval: 2m
    timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: victoria-operator
spec:
    targetNamespace: o11y
    dependsOn:
        - name: victoria-operator-crds
          namespace: o11y
    path: ./kubernetes/apps/o11y/victoria/app
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    interval: 1h
    retryInterval: 2m
    timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: victoria-metrics
spec:
    targetNamespace: o11y
    dependsOn:
        - name: victoria-operator
          namespace: o11y
    path: ./kubernetes/apps/o11y/victoria/metrics
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    interval: 1h
    retryInterval: 2m
    timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: victoria-logs-datasource
spec:
    targetNamespace: o11y
    dependsOn:
        - name: victoria-operator
          namespace: o11y
        - name: victoria-logs
          namespace: o11y
    path: ./kubernetes/apps/o11y/victoria/logs
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    interval: 1h
    retryInterval: 2m
    timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: victoria-traces
spec:
    targetNamespace: o11y
    dependsOn:
        - name: victoria-operator
          namespace: o11y
    path: ./kubernetes/apps/o11y/victoria/traces
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    interval: 1h
    retryInterval: 2m
    timeout: 5m
