---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lifttrace
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lifttrace-secret
    creationPolicy: Owner
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TOKEN_ENC_KEY: "{{ .TOKEN_ENC_KEY }}"
        RECOVERY_TOKEN: "{{ .RECOVERY_TOKEN }}"
  dataFrom:
    - extract:
        key: lifttrace
