apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pocketid.internal_pocketidinstances.yaml
  - pocketid.internal_pocketidoidcclients.yaml
  - pocketid.internal_pocketidusergroups.yaml
  - pocketid.internal_pocketidusers.yaml
