---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  values:
    domain: goyangi.io
    ttl: 1
    service:
      ipFamily: IPv4
      ipFamilyPolicy: SingleStack
      loadBalancerClass: tailscale
      port: 53
      type: LoadBalancer
    watchedResources: ["HTTPRoute"]
