---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: opencloud
spec:
  clientID: opencloud
  isPublic: true
  pkceEnabled: true
  callbackUrls:
    - https://opencloud.goyangi.io/oidc-callback.html
    - oc://ios.opencloud.eu
    - oc:android.opencloud.eu
  logoutCallbackUrls:
    - https://opencloud.goyangi.io
    - oc://ios.opencloud.eu
    - oc:android.opencloud.eu
  allowedUserGroups:
    - name: user
