---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: github
spec:
  image: ghcr.io/github/github-mcp-server:latest
  transport: streamable-http
  env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: toolhive-github
          key: GITHUB_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  groupRef:
    name: mcp-tools
