---
apiVersion: v1
kind: Service
metadata:
  name: agentgateway-proxy
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: ai
  ports:
    - name: https
      port: 443
      targetPort: 443
