apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: macro
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: macro-secret
    template:
      data:
        S3_ACCESS_KEY: "{{ .GARAGE_ROOT_USER }}"
        S3_SECRET_KEY: "{{ .GARAGE_ROOT_PASSWORD }}"
        DOMAIN_CLIENT_ID: "{{ .DOMAIN_CLIENT_ID }}"
        DOMAIN_CLIENT_SECRET: "{{ .DOMAIN_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: garage
    - extract:
        key: domain
