---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: sonarr
spec:
  clientID: sonarr
  description: Sonarr administration
  callbackUrls:
    - https://sonarr.goyangi.io/oauth2/callback
  logoutCallbackUrls:
    - https://sonarr.goyangi.io
  allowedUserGroups:
    - name: admin
  secret:
    name: sonarr-oidc
