---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    linkerd.io/inject: disabled
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    istio-injection: disabled
