---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./buildbarn/ks.yaml
  - ./scheduler/ks.yaml
  - ./browser/ks.yaml
  # - ./worker/ks.yaml  # disabled: using public runners
