---
apiVersion: v1
kind: Namespace
metadata:
  name: buildbarn
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/vpa-update-mode: Auto
    goldilocks.fairwinds.com/vpa-resource-policy: '{"containerPolicies":[{"containerName":"*","maxAllowed":{"cpu":"100m","memory":"512Mi"}}]}'
  labels:
    goldilocks.fairwinds.com/enabled: 'true'
