---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chaski-secret
    template:
      data:
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        RADARR_PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        READARR_PUSHOVER_TOKEN: "{{ .READARR_PUSHOVER_TOKEN }}"
        WHISPARR_PUSHOVER_TOKEN: "{{ .WHISPARR_PUSHOVER_TOKEN }}"
        SEERR_PUSHOVER_TOKEN: "{{ .SEERR_PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: readarr
    - extract:
        key: whisparr
    - extract:
        key: seerr
    - extract:
        key: pushover
