---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-cluster
spec:
  hostname: k8s-connector
  subnetRouter:
    advertiseRoutes:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 192.168.69.0/24
      - 192.168.1.0/24
