---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-init
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner-init
    template:
      data:
        CONFIG_NAME: "forgejo-runner"
        CONFIG_INSTANCE: "https://forgejo.goyangi.io"
        CONFIG_TOKEN: "{{ .FORGEJO_RUNNER_REGISTRATION_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo