# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: print
spec:
  chartRef:
    kind: OCIRepository
    name: print
  interval: 1h
  values:
    controllers:
      print:
        type: cronjob
        cronjob:
          schedule: "0 13 * * 0"
          timeZone: Australia/Sydney
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: alpine
              tag: 3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
            command: ["/bin/sh", "/config/print.sh"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
        pod:
          restartPolicy: OnFailure
    defaultPodOptions:
      securityContext:
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        type: configMap
        name: print-configmap
        globalMounts:
          - path: /config
