---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-secret
    creationPolicy: Owner
    template:
      data:
        MARIADB_ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        MARIADB_REPL_PASSWORD: "{{ .MARIADB_REPL_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .VERSITYGW_ROOT_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VERSITYGW_ROOT_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: mariadb
    - extract:
        key: versitygw
