---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: free-games-pushover
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: free-games-pushover
    creationPolicy: Owner
  data:
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: pushover
        property: add more/PUSHOVER_USER_KEY
    - secretKey: PUSHOVER_API_TOKEN
      remoteRef:
        key: pushover
        property: add more/PUSHOVER_API_TOKEN
