---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lk-jwt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: lk-jwt
  values:
    controllers:
      lk-jwt:
        containers:
          app:
            image:
              repository: ghcr.io/element-hq/lk-jwt-service
              tag: 0.4.3
            env:
              LIVEKIT_URL: ws://livekit-app.default.svc.cluster.local:7880
              LK_JWT_PORT: "8080"
              LIVEKIT_FULL_ACCESS_HOMESERVERS: goyangi.io
            envFrom:
              - secretRef:
                  name: livekit-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
    service:
      app:
        controller: lk-jwt
        ports:
          http:
            port: 8080
