---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate
    creationPolicy: Owner
    template:
      metadata:
        labels:
          renovate-operator.mogenius.com/allow-ref: "true"
      data:
        APP_ID: "{{ .GITHUB_BOT_APP_ID }}"
        INSTALL_ID: "{{ .GITHUB_BOT_INSTALLATION_ID }}"
        PEM: "{{ .GITHUB_BOT_APP_PRIVATE_KEY }}"
        FORGEJO_TOKEN: "{{ .FORGEJO_TOKEN }}"
        OCHARTED_USERNAME: "{{ .OCHARTED_USERNAME }}"
        OCHARTED_PASSWORD: "{{ .OCHARTED_PASSWORD }}"
  dataFrom:
    - extract:
        key: github-bot
    - extract:
        key: forgejo
    - extract:
        key: ocharted
