---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-bot-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-github-bot-pem
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: github-bot

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: renovate-github-auth-token
spec:
  appID: "1109230"
  installID: "59452502"
  auth:
    privateKey:
      secretRef:
        name: renovate-github-bot-pem
        key: BOT_APP_PRIVATE_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-auth-token
spec:
  target:
    name: renovate-github-auth-token
    creationPolicy: Owner
    template:
      metadata:
        labels:
          renovate-operator.mogenius.com/allow-ref: "true"
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: bot-goyangi
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: renovate-github-auth-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-ocharted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-ocharted
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ocharted

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-forgejo
    creationPolicy: Owner
    template:
      data:
        RENOVATE_TOKEN: "{{ .FORGEJO_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo
