---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zigbee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee
  minReplicas: 0
  maxReplicas: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Object
      object:
        describedObject:
          apiVersion: v1
          kind: Namespace
          name: default
        metric:
          name: zigbee_controller_available
        target:
          type: Value
          value: "1"
