---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: headplane
spec:
  clientID: headplane
  callbackUrls:
    - https://headplane.goyangi.io/admin/oidc/callback
  allowedUserGroups:
    - name: admin
      namespace: default
  secret:
    name: headplane-oidc
    keys:
      clientSecret: HEADPLANE_OIDC_CLIENT_SECRET
