---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-notebook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-notebook-secret
    template:
      data:
        OPEN_NOTEBOOK_ENCRYPTION_KEY: "{{ .OPEN_NOTEBOOK_ENCRYPTION_KEY }}"
        SURREAL_USER: "{{ .SURREAL_USER }}"
        SURREAL_PASSWORD: "{{ .SURREAL_PASSWORD }}"
  dataFrom:
    - extract:
        key: open-notebook
    - extract:
        key: surrealdb
