---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headscale-gateway
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headscale-gateway-auth
    template:
      data:
        TS_AUTHKEY: '{{ .HEADSCALE_GATEWAY_AUTHKEY }}'
  dataFrom:
    - extract:
        key: headscale-gateway
