---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: openclaw-webhook-config
    files:
      - hooks.yaml=./resources/hooks.yaml
      - github.sh=./resources/github.sh
      - opencode.sh=./resources/opencode.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
