---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookorbit-secret
    creationPolicy: Owner
    template:
      data:
        POSTGRES_HOST: &dbHost postgres-rw.storage.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbName bookorbit
        POSTGRES_USER: &dbUser "{{ .BOOKORBIT_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .BOOKORBIT_POSTGRES_PASSWORD }}"
        JWT_SECRET: "{{ .BOOKORBIT_JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .BOOKORBIT_SETUP_BOOTSTRAP_TOKEN }}"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: bookorbit
    - extract:
        key: cloudnative-pg
