---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: bookorbit
spec:
  clientID: bookorbit
  isPublic: false
  callbackUrls:
    - https://bookorbit.goyangi.io/oauth2-callback
  logoutCallbackUrls:
    - https://bookorbit.goyangi.io
  secret:
    name: bookorbit-oidc
