---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgresql://{{ .OUTLINE_POSTGRES_USER }}:{{ .OUTLINE_POSTGRES_PASSWORD }}@postgres-rw.storage.svc.cluster.local:5432/outline"
        SECRET_KEY: "{{ .OUTLINE_SECRET_KEY }}"
        UTILS_SECRET: "{{ .OUTLINE_UTILS_SECRET }}"
        INIT_POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
        INIT_POSTGRES_DBNAME: outline
        INIT_POSTGRES_USER: "{{ .OUTLINE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OUTLINE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: outline
    - extract:
        key: cloudnative-pg
