---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-sandbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-sandbox-secret
    creationPolicy: Owner
    template:
      data:
        authorized_keys: "{{ .SANDBOX_SSH_PUBLIC_KEY }}"
        OP_SERVICE_ACCOUNT_TOKEN: "{{ .HAWOW_OP_SERVICE_ACCOUNT_TOKEN }}"
  dataFrom:
    - extract:
        key: 1password
    - extract:
        key: openclaw
