---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: litellm-chatgpt-auth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: miroir-replicated
    volumeMode: Filesystem

