---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMGuardrail
metadata:
    name: presidio-pre
spec:
    guardrailName: presidio-pii-pre
    guardrail: presidio
    mode: pre_call
    defaultOn: true
    apiBase: http://presidio.ai.svc.cluster.local:3000
    params:
        mock_redacted_text:
            text: "[REDACTED]"
---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMGuardrail
metadata:
    name: presidio-post
spec:
    guardrailName: presidio-pii-post
    guardrail: presidio
    mode: post_call
    defaultOn: true
    apiBase: http://presidio.ai.svc.cluster.local:3000
    params:
        mock_redacted_text:
            text: "[REDACTED]"
