---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboard
  - ./models
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./litellmproxy.yaml
  - ./oidc.yaml
  - ./prometheusrule.yaml
  - ./pvc.yaml
  - ./servicemonitor.yaml
  - ./vmrule.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: litellm
    patch: |-
      - op: remove
        path: /spec/dataSource
      - op: remove
        path: /spec/dataSourceRef
