---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: litellm-data
spec:
    accessModes: ["ReadWriteOnce"]
    resources:
        requests:
            storage: 5Gi
    storageClassName: miroir-replicated
