---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-operator
  namespace: security
spec:
  targetNamespace: security
  interval: 1h
  path: ./kubernetes/apps/security/kanidm-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-instance
  namespace: security
spec:
  targetNamespace: security
  dependsOn:
    - name: kanidm-operator
      namespace: security
  interval: 1h
  path: ./kubernetes/apps/security/kanidm-operator/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
