---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-webhook-token-secret
  namespace: flux-system
type: Opaque
stringData:
  token: "f55181dea5df711eae503a31a90bf38fd95134ac5ad48070f5b56587d659d572"
