---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/receiver_v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: forgejo-webhook
  namespace: flux-system
spec:
  events:
    - push
  interval: 10m
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system-private
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: cluster-apps-private
  secretRef:
    name: forgejo-webhook-token-secret
  type: generic
