---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nativelink
spec:
  chartRef:
    kind: OCIRepository
    name: nativelink
  interval: 10m
  install:
    timeout: 15m
  upgrade:
    timeout: 15m
  values:
    serviceAccount:
      annotations: {}

    cas:
      replicaCount: 1
      logLevel: info
      cloudProvider: filesystem

      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi

      eviction:
        acMemoryMaxBytes: "100mb"
        acMemoryEvictBytes: "20mb"
        acMemoryMaxCount: 150000
        acFsMaxBytes: "2gb"
        acFsEvictBytes: "400mb"
        casMemoryMaxBytes: "1gb"
        casMemoryEvictBytes: "200mb"
        casMemoryMaxCount: 100000
        casFsUpperMaxBytes: "20gb"
        casFsUpperEvictBytes: "4gb"
        casFsMaxConcurrentWrites: 50
        casFsLowerMaxBytes: "60gb"
        casFsLowerEvictBytes: "12gb"

      persistentVolume:
        enabled: false

      rbe:
        enabled: true
        defaultCpuCount: "1000"

      service:
        type: ClusterIP
        grpcPort: 50051

      nodeSelector:
        node.kubernetes.io/nodepool: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      tolerations:
        - key: nodepool
          operator: Equal
          value: "true"
          effect: NoSchedule

    workers:
      casFsMaxBytes: 30G
      maxActionTimeout: 3600

      specs:
        - name: default
          initImage: ghcr.io/tracemachina/nativelink-worker-init
          replicas: 1
          podImage: ubuntu:26.04
          imagePullPolicy: IfNotPresent
          logLevel: info
          nodeSelector:
            node.kubernetes.io/nodepool: "true"
            kubernetes.io/arch: amd64
            kubernetes.io/os: linux
          preferSpot: true
          tolerations:
            - key: nodepool
              operator: Equal
              value: "true"
              effect: NoSchedule
          resources:
            limits:
              cpu: "5"
              ephemeral-storage: 30Gi
              memory: 16Gi
            requests:
              cpu: "4"
              ephemeral-storage: 30Gi
              memory: 12Gi
          platformProperties:
            osFamily: Linux
            containerImage: ubuntu:26.04
            cpuCount: 5000
            memoryKb: 16000000
            gpuCount: 0
            ISA: x86-64
          volumes:
            - emptyDir: {}
              name: work-volume
          volumeMounts:
            - mountPath: /tmp/nativelink
              name: work-volume
