---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
spec:
  chartRef:
    kind: OCIRepository
    name: trilium
  interval: 10m
  values:
    controllers:
      trilium:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/triliumnext/trilium
              tag: v0.103.0
            env:
              TZ: Australia/Sydney
              TRILIUM_DATA_DIR: /home/node/trilium-data
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - trilium.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    persistence:
      data:
        existingClaim: trilium
        globalMounts:
          - path: /home/node/trilium-data
