---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: towonel-operator-secret
    creationPolicy: Owner
  data:
    - secretKey: TOWONEL_API_KEY
      remoteRef:
        key: towonel
        property: TOWONEL_API_KEY
