---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: romarr-secret
    creationPolicy: Owner
    template:
      data:
        LIBRARY_API_KEY: "{{ .ROMM_API_TOKEN }}"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        QBITTORRENT_USER: "{{ .QBITTORRENT_USER }}"
        QBITTORRENT_PASS: "{{ .QBITTORRENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: romm
    - extract:
        key: prowlarr
    - extract:
        key: qbittorrent
