---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: romarr
spec:
  clientID: romarr
  callbackUrls:
    - https://romarr.goyangi.io/oauth2/callback
  logoutCallbackUrls:
    - https://romarr.goyangi.io
  allowedUserGroups:
    - name: user
  secret:
    name: romarr-oidc
    keys:
      clientSecret: client-secret
