---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trino-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trino-worker
  minReplicas: 0
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Object
      object:
        describedObject:
          apiVersion: v1
          kind: Service
          name: trino
        metric:
          name: trino_running_queries
        target:
          type: Value
          value: "1"
