---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      data:
        APP_ID: "{{ .RENOVATE_APP_ID }}"
        APP_PRIVATE_KEY: "{{ .RENOVATE_PRIVATE_KEY }}"
        APP_INSTALLATION_ID: "{{ .RENOVATE_INSTALLATION_ID }}"
  dataFrom:
    - extract:
        key: renovate
