---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  schedule: "0 * * * *"
  provider:
    name: github
  secretRef: renovate-secret
  image: ghcr.io/renovatebot/renovate:latest
  parallelism: 3
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_AUTODISCOVER
      value: "false"
    - name: RENOVATE_REPOSITORIES
      value: '["solanyn/mono","solanyn/home-ops","solanyn/containers"]'
