---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  schedule: "0 * * * *"
  provider:
    name: github
  secretRef: renovate-secret
  image: ghcr.io/renovatebot/renovate:latest
  parallelism: 3
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_AUTODISCOVER
      value: "false"
    - name: RENOVATE_REPOSITORIES
      value: '["solanyn/mono","solanyn/home-ops","solanyn/containers"]'
    - name: RENOVATE_APP_ID
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: APP_ID
    - name: RENOVATE_APP_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: APP_PRIVATE_KEY
    - name: RENOVATE_APP_INSTALLATION_ID
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: APP_INSTALLATION_ID
---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  schedule: "30 * * * *"
  provider:
    name: gitea
  secretRef: renovate-forgejo-secret
  image: ghcr.io/renovatebot/renovate:latest
  parallelism: 1
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: gitea
    - name: RENOVATE_ENDPOINT
      value: https://forgejo.goyangi.io
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: RENOVATE_AUTODISCOVER
      value: "false"
    - name: RENOVATE_REPOSITORIES
      value: '["andrew/nix-darwin"]'
    - name: RENOVATE_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-forgejo-secret
          key: TOKEN
