---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gamarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gamarr-secret
    creationPolicy: Owner
    template:
      data:
        QB_PASS: "{{ .QBITTORRENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: qbittorrent
