apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: headscale
  namespace: network
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: headscale-app
  httpUpgrade:
    - type: DERP
    - type: websocket
    - type: tailscale-control-protocol
  timeout:
    http:
      connectionIdleTimeout: 1h
      maxStreamDuration: 0s
