---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: headscale
spec:
  clientID: headscale
  callbackUrls:
    - https://headscale.goyangi.io/oidc/callback
  allowedUserGroups:
    - name: admin
      namespace: default
  secret:
    name: headscale-oidc
    keys:
      clientSecret: HEADSCALE_OIDC_CLIENT_SECRET
