---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kan
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kan-secret
    creationPolicy: Owner
    template:
      data:
        POSTGRES_URL: "postgresql://{{ .KAN_POSTGRES_USER }}:{{ .KAN_POSTGRES_PASSWORD }}@postgres-rw.storage.svc.cluster.local:5432/kan"
        INIT_POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
        INIT_POSTGRES_DBNAME: kan
        INIT_POSTGRES_USER: "{{ .KAN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .KAN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: kan
    - extract:
        key: cloudnative-pg
