---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-mcp
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-mcp
  interval: 1h
  values:
    controllers:
      grafana-mcp:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: grafana/mcp-grafana
              tag: 0.12.1@sha256:02a6a43958d55c7930f86ee2437c5517418220b9ff4a3cd589d46fe287450373
            args:
              - -t
              - streamable-http
              - --address
              - 0.0.0.0:8000
            env:
              GRAFANA_URL: http://grafana-service.o11y.svc:3000
              GRAFANA_SERVICE_ACCOUNT_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: grafana-sa-token
                    key: token
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: grafana-mcp
        ports:
          http:
            port: 8000
