---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: grimmory
spec:
  mariaDbRef:
    name: mariadb
    namespace: storage
  passwordSecretKeyRef:
    name: grimmory-secret
    key: GRIMMORY_DB_PASS
  host: "%"
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: grimmory
spec:
  mariaDbRef:
    name: mariadb
    namespace: storage
  name: grimmory
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grimmory
spec:
  mariaDbRef:
    name: mariadb
    namespace: storage
  privileges:
    - ALL PRIVILEGES
  database: grimmory
  table: "*"
  username: grimmory
  host: "%"
  grantOption: false
