# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grimmory-secret
    creationPolicy: Owner
    template:
      data:
        GRIMMORY_DB_USER: "{{ .GRIMMORY_DB_USER }}"
        GRIMMORY_DB_PASS: "{{ .GRIMMORY_DB_PASS }}"
        DATABASE_URL: "jdbc:mariadb://mariadb.storage.svc.cluster.local:3306/grimmory"
        DATABASE_USERNAME: "{{ .GRIMMORY_DB_USER }}"
        DATABASE_PASSWORD: "{{ .GRIMMORY_DB_PASS }}"
  dataFrom:
    - extract:
        key: grimmory
