---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grimmory
spec:
  clientID: grimmory
  isPublic: true
  callbackUrls:
    - https://grimmory.goyangi.io/oauth2-callback
  logoutCallbackUrls:
    - https://grimmory.goyangi.io
  secret:
    name: grimmory-oidc
