---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  chartRef:
    kind: OCIRepository
    name: unpoller
  interval: 1h
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v3.3.3@sha256:9a4e1b61de1103044e62a41b6c3181caae94a6a3dc48cb39676373eb05b781a8
            env:
              TZ: Australia/Sydney
              UP_UNIFI_DEFAULT_URL: https://192.168.1.1
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_TIMEOUT: 30s
              UP_UNIFI_DEFAULT_SAVE_SITES: false
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:9090
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 9090
                  initialDelaySeconds: 120
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
            interval: 2m
            scrapeTimeout: 10s
