apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lakekeeper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lakekeeper-secret
    template:
      data:
        LAKEKEEPER__PG_DATABASE_URL_READ: postgresql://lakekeeper@postgres-r.storage.svc.cluster.local:5432/lakekeeper?sslmode=require
        LAKEKEEPER__PG_DATABASE_URL_WRITE: postgresql://lakekeeper@postgres-rw.storage.svc.cluster.local:5432/lakekeeper?sslmode=require
        LAKEKEEPER__PG_ENCRYPTION_KEY: "{{ .LAKEKEEPER_SECRET_KEY }}"
        LAKEKEEPER__AUTHZ_BACKEND: allowall
        LAKEKEEPER__BASE_URI: http://lakekeeper.storage.svc.cluster.local:8181
        LAKEKEEPER__S3__ENDPOINT: http://garage.storage.svc.cluster.local:3900
        LAKEKEEPER__S3__ACCESS_KEY: "{{ .GARAGE_ROOT_USER }}"
        LAKEKEEPER__S3__SECRET_KEY: "{{ .GARAGE_ROOT_PASSWORD }}"
        LAKEKEEPER__S3__REGION: us-east-1
        RUST_LOG: info
        INIT_POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
        INIT_POSTGRES_DBNAME: lakekeeper
        INIT_POSTGRES_USER: lakekeeper
        INIT_POSTGRES_PASS: "{{ .LAKEKEEPER_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lakekeeper
    - extract:
        key: garage
    - extract:
        key: cloudnative-pg
