---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: element-web
spec:
  chartRef:
    kind: OCIRepository
    name: element-web
  interval: 1h
  values:
    controllers:
      element-web:
        containers:
          app:
            image:
              repository: docker.io/vectorim/element-web
              tag: v1.12.17@sha256:f4a81a24d49a9c5b97e02e77a3013ec799873e500e69041078a28be98e4f1280
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - element.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: element-web
                port: 80
    persistence:
      config:
        type: configMap
        name: element-web
        globalMounts:
          - path: /app/config.json
            subPath: config.json
    configMaps:
      config:
        data:
          config.json: |
            {
              "default_server_config": {
                "m.homeserver": {
                  "base_url": "https://matrix.goyangi.io",
                  "server_name": "goyangi.io"
                }
              },
              "brand": "Element",
              "disable_guests": true,
              "disable_3pid_login": true
            }
