---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: ovh
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        name: ovh-secret
        template:
            data:
                OVH_APPLICATION_KEY: "{{ .OVH_TOFU_APPLICATION_KEY }}"
                OVH_APPLICATION_SECRET: "{{ .OVH_TOFU_APPLICATION_SECRET }}"
                OVH_CONSUMER_KEY: "{{ .OVH_TOFU_CONSUMER_KEY }}"
    dataFrom:
        - extract:
              key: ovhcloud
