---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/raw.githubusercontent.com/flux-iac/tofu-controller/main/docs/api/v1alpha2/terraform.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
    name: ovh
spec:
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    path: ./opentofu/ovh
    interval: 10m
    planOnly: true
    destroyResourcesOnDeletion: false
    runnerPodTemplate:
        spec:
            envFrom:
                - secretRef:
                      name: ovh-secret
