---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/alerts

resources:
    - ./namespace.yaml
    - ./hermes/ks.yaml
    - ./honcho/ks.yaml
    - ./litellm-operator/ks.yaml
    - ./litellm/ks.yaml
    - ./llmkube/ks.yaml
    - ./mlx/ks.yaml
    - ./omlox/ks.yaml
    - ./open-notebook/ks.yaml
    - ./presidio/ks.yaml
