---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/vpa-update-mode: Auto
    goldilocks.fairwinds.com/vpa-resource-policy: '{"containerPolicies":[{"containerName":"*","maxAllowed":{"cpu":"500m","memory":"2Gi"}}]}'
  labels:
    goldilocks.fairwinds.com/enabled: 'true'
