---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage-operator-system
resources:
    - namespace.yaml
    - garage-secret-copy.yaml
    - garage-cluster-handle.yaml
    - reference-grant.yaml
