---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: kubectl
  namespace: o11y
spec:
  image: docker.io/rohitghumare64/kubectl-mcp-server:14f9c13@sha256:2cedffbd1b8439548d02342170c0570f2ecc1120ecf17a7a450ff2691f789b20
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount: kubectl-mcp-readonly
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - --transport
            - streamable-http
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --read-only
          env:
            - name: MCP_K8S_PROVIDER
              value: in-cluster
            - name: PYTHONUNBUFFERED
              value: "1"
  groupRef:
    name: mcp-tools
