---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ${KOPIUR_ACCESSMODES:=ReadWriteOnce}
  resources:
    requests:
      storage: ${KOPIUR_CAPACITY:=5Gi}
  storageClassName: ${KOPIUR_STORAGECLASS:=miroir-replicated}
