---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodepool-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nodepool-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: nodepool-machine-config
            items:
              - key: NODEPOOL_USER_DATA
                templateAs: KeysAndValues
  dataFrom:
    - extract:
        key: talos
    - extract:
        key: headscale-gateway
