---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodepool-machine-config
data:
  NODEPOOL_USER_DATA: |
    {{ list
      "version: v1alpha1"
      "machine:"
      "  type: worker"
      (printf "  token: %s" .MACHINE_TOKEN)
      "  ca:"
      (printf "    crt: %s" .MACHINE_CA_CRT)
      "  kubelet:"
      "    defaultRuntimeSeccompProfileEnabled: true"
      "    disableManifestsDirectory: true"
      "    extraArgs:"
      "      rotate-server-certificates: \"true\""
      "    nodeIP:"
      "      validSubnets:"
      "        - 100.69.0.0/16"
      "  nodeLabels:"
      "    node-role.kubernetes.io/burst: \"true\""
      "  nodeTaints:"
      "    burst: \"true:NoSchedule\""
      "  install:"
      "    image: factory.talos.dev/installer/4a0d65c669d46663f377e7161e50cfd570c401f26fd9e7bda34a0216b6f1922b:v1.12.6"
      "    wipe: false"
      "  features:"
      "    rbac: true"
      "    hostDNS:"
      "      enabled: true"
      "      forwardKubeDNSToHost: true"
      "      resolveMemberNames: true"
      "    kubePrism:"
      "      enabled: true"
      "      port: 7445"
      "  kernel:"
      "    modules:"
      "      - name: nbd"
      "  files:"
      "    - op: create"
      "      path: /etc/cri/conf.d/20-customization.part"
      "      content: |"
      "        [plugins.\"io.containerd.cri.v1.images\"]"
      "          discard_unpacked_layers = false"
      "    - op: create"
      "      path: /var/etc/tailscale/auth.env"
      "      permissions: 0o600"
      "      content: |"
      (printf "        TS_AUTHKEY=%s" .HEADSCALE_GATEWAY_AUTHKEY)
      "        TS_EXTRA_ARGS=--login-server=https://headscale.goyangi.io --accept-routes"
      "cluster:"
      (printf "  id: %s" .CLUSTER_ID)
      (printf "  secret: %s" .CLUSTER_SECRET)
      "  controlPlane:"
      "    endpoint: https://192.168.42.120:6443"
      "  clusterName: home"
      "  network:"
      "    cni:"
      "      name: none"
      "    dnsDomain: cluster.local"
      "    podSubnets:"
      "      - 10.42.0.0/16"
      "    serviceSubnets:"
      "      - 10.43.0.0/16"
      (printf "  token: %s" .CLUSTER_TOKEN)
      "  ca:"
      (printf "    crt: %s" .CLUSTER_CA_CRT)
      "  discovery:"
      "    enabled: false"
      "  proxy:"
      "    disabled: true"
    | join "\n" | b64enc }}
