---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
    name: volsync
spec:
    allowedNamespaces:
        all: true
    backend:
        filesystem:
            path: /repository
            volume:
                nfs:
                    path: /mnt/world/volsynckopia
                    server: nas.internal
    catalog:
        fallbackNamespace: kopiur-system
        periodicRefresh: true
        refreshInterval: 1h
    create:
        enabled: true
    credentialProjection:
        allowed: true
    encryption:
        passwordSecretRef:
            name: kopiur-repository-secret
            namespace: kopiur-system
            key: KOPIA_PASSWORD
    identityDefaults:
        hostnameExpr: "'volsync.volsync-system.svc.cluster.local'"
        usernameExpr: "'volsync'"
    maintenance:
        enabled: true
        namespace: kopiur-system
        schedule:
            full:
                cron: "0 3 * * *"
                jitter: 1h
            quick:
                cron: "0 */6 * * *"
                jitter: 30m
            timezone: Australia/Sydney
        takeoverPolicy: Force
    moverDefaults:
        securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    mode: ReadWrite
