---
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudnative-pg-bucket
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-bucket
          image: amazon/aws-cli:2.27.41
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloudnative-pg-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudnative-pg-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          command:
            - /bin/sh
            - -ec
          args:
            - |
              endpoint=http://nas.internal:9000
              if aws s3api head-bucket --bucket cloudnative-pg --endpoint-url "$endpoint"; then
                exit 0
              fi
              aws s3api create-bucket --bucket cloudnative-pg --endpoint-url "$endpoint"
