apiVersion: v1
kind: Secret
metadata:
  name: s3-versitygw-ca
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXjCCAkagAwIBAgIRAMotnZ7sD/z04WMoFrNmmJ4wDQYJKoZIhvcNAQELBQAw
    HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMjYwODA4MDYyOTQ0
    WhcNMjcwODA4MDYyOTQ0WjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
    VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANq1YZIgK4+tby2v4C2H
    OGubEfVMDKJTvrzqPqQhWKTaPngo8qwKSzkb+U4bRFIT+bz1DXzcz+vlAmGR710O
    hM6d1FtPHqb//5Zq3DKiRjlPggw1rIZQQcwPmFX4RNWWyYlEJk3eDQJvVl8QCGH+
    CkRyQBZIqQEFDI9zZdGwPgVzU5xDEBVcJDkMzFoSyClETpHAmjV6Z5aP5jvYM84k
    ISbuf54AsSWOF7MQeo/xY3ETesxmLoGIDlCrJc2kiaNylpUQfnXyyMtshXCZeyVE
    3iFZBbw/cgnjP2U+DdQmoPXttaRR++QJ8iqqWY1Kt9hKqAzv9uDlSYmjMtFjL3LB
    d8ECAwEAAaOBlDCBkTAOBgNVHQ8BAf8EBAMCA7gwEwYDVR0lBAwwCgYIKwYBBQUH
    AwEwDAYDVR0TAQH/BAIwADBcBgNVHREEVTBTglE4Yzg3Y2Y5NzBhNGRmMTRmZDY1
    ZmJmZjIwOGZjNjA1My43OTEzNGUzZDNhZmNkNGRmY2QxMDBmNjY3MTk1NjdkMy50
    cmFlZmlrLmRlZmF1bHQwDQYJKoZIhvcNAQELBQADggEBAFtXAotKm4s8sUWh9/jp
    mFt476Z3CzGjmF7qpSm3hxngAr9LjPwRk1mswUk0IhtQaAILM5inxHYQQiDBgBVV
    4PzbWQhdsIomXphHLx6cP7WKxneVoI8s1zb/qKKuqFyj4ek+ytevLhsaoVXvraxO
    tx4q6YuHcJKlYRkOdl+MOrqFPrRDVjjw/QuTiDidvoA0NlVGlpvaCPlI/7pJe6ly
    5bpdHbVUaJOHv191uH9H4NJjmUgLY62N4p63RkvBTnepiDwC1LU0TXAPIEIljsDJ
    6Fqr2CX179l3MFaz+AUZ2xXDOhambmxe27fB0iLZqBTTEWDknFVoJqk6K3Hv6yh+
    ocA=
    -----END CERTIFICATE-----
