---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: presidio
spec:
  chartRef:
    kind: OCIRepository
    name: presidio
  interval: 1h
  values:
    controllers:
      presidio:
        containers:
          analyzer:
            image:
              repository: ghcr.io/solanyn/presidio-analyzer-sm
              tag: 2.2.362
            ports:
              - name: http
                containerPort: 3000
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1Gi
          anonymizer:
            image:
              repository: mcr.microsoft.com/presidio-anonymizer
              tag: 2.2.4
              digest: sha256:607c5a8f7918c956fe6385a8d6888075b7198ae2329574cbb37526e851521d20
            env:
              - name: PORT
                value: "3001"
            ports:
              - name: http
                containerPort: 3001
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 3001
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      presidio:
        controller: presidio
        ports:
          analyzer:
            port: 3000
          anonymizer:
            port: 3001
