---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: romarr
spec:
  targetNamespace: default
  components:
    - ../../../../components/kopiur
  dependsOn:
    - name: romm
      namespace: default
    - name: prowlarr
      namespace: default
    - name: qbittorrent
      namespace: default
    - name: pocket-id-resources
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/romarr/app
  postBuild:
    substitute:
      APP: romarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
