---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: retain-hermes-matrix-data
        annotations:
          kustomize.toolkit.fluxcd.io/prune: disabled
    target:
      kind: PersistentVolumeClaim
