---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
  namespace: kubeflow
data:
  defaultPipelineRoot: "minio://kfp-pipelines/v2/artifacts"
  providers: |
    minio:
      default:
        endpoint: "garage.storage.svc.cluster.local:3900"
        region: "us-east-1"
        disableSSL: true
        forcePathStyle: true
        credentials:
          fromEnv: false
          secretRef:
            secretName: "mlpipeline-minio-artifact"
            accessKeyKey: "accesskey"
            secretKeyKey: "secretkey"
