---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpackerr-secret
    creationPolicy: Owner
    template:
      data:
        UN_SONARR_0_URL: http://sonarr.default.svc.cluster.local:80
        UN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
