---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana-mcp
  namespace: o11y
spec:
  image: grafana/mcp-grafana:1.1.0@sha256:f21a19cebbfa7c3a76ef1746171e5ffc3601064e432f593e7c6cb526e5216e5f
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.o11y.svc:3000
  secrets:
    - name: grafana-sa-token
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  groupRef:
    name: mcp-tools
