# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml

configMapGenerator:
  - name: romm-tools-script
    files:
      - import.py=resources/import.py
      - ntool_wrapper.py=resources/ntool_wrapper.py
generatorOptions:
  disableNameSuffixHash: true
