---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: kelos-session-auth
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        name: kelos-session-auth
        creationPolicy: Owner
        template:
            data:
                token: "{{ .KELOS_SESSION_TOKEN }}"
    dataFrom:
        - extract:
              key: kelos
