---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes
    creationPolicy: Owner
    template:
      data:
        BLUEBUBBLES_PASSWORD: "{{ .BLUEBUBBLES_PASSWORD }}"
        HONCHO_API_KEY: "{{ .HONCHO_API_KEY }}"
        MATRIX_ACCESS_TOKEN: "{{ .MATRIX_BOT_ACCESS_TOKEN }}"
        MATRIX_DEVICE_ID: "{{ .MATRIX_BOT_DEVICE_ID }}"
        OP_SERVICE_ACCOUNT_TOKEN: "{{ .OP_SERVICE_ACCOUNT_TOKEN }}"
        OPENAI_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
  data:
    - secretKey: BLUEBUBBLES_ALLOWED_USERS
      remoteRef:
        key: hermes
        property: HERMES_BLUEBUBBLES_ALLOWED_USERS
  dataFrom:
    - extract:
        key: 1password
    - extract:
        key: bluebubbles
    - extract:
        key: honcho
    - extract:
        key: litellm
    - extract:
        key: matrix
