---
apiVersion: v1
kind: Service
metadata:
  name: hermes
spec:
  ports:
    - name: http
      port: 8645
      targetPort: 8645
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hermes-1
  labels:
    kubernetes.io/service-name: hermes
addressType: IPv4
ports:
  - name: http
    port: 8645
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.10.30"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes
spec:
  hostnames:
    - hermes.goyangi.io
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hermes
          port: 8645
