---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: unifi-mcp
  namespace: o11y
spec:
  image: ghcr.io/sirkirby/unifi-network-mcp:0.24.1@sha256:7033f372d7a9292eeea361821a37f68a2a235e7e63183fd13fe9a78da7072030
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 3000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  env:
    - name: UNIFI_API_KEY
      valueFrom:
        secretKeyRef:
          name: unifi-mcp-secret
          key: UNIFI_API_KEY
    - name: UNIFI_HOST
      valueFrom:
        secretKeyRef:
          name: unifi-mcp-secret
          key: UNIFI_HOST
    - name: UNIFI_VERIFY_SSL
      valueFrom:
        secretKeyRef:
          name: unifi-mcp-secret
          key: UNIFI_VERIFY_SSL
  groupRef:
    name: mcp-tools
