---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: unifi-mcp
  namespace: o11y
spec:
  image: ghcr.io/sirkirby/unifi-network-mcp:0.29.3@sha256:4549c6f5129de070c070d19ff6a82b155449154c846cdd09947e66edb0c86c3d
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 3000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  secrets:
    - name: unifi-mcp-secret
      key: UNIFI_API_KEY
      targetEnvName: UNIFI_API_KEY
  env:
    - name: UNIFI_HOST
      value: https://192.168.1.1
    - name: UNIFI_VERIFY_SSL
      value: "false"
  groupRef:
    name: mcp-tools
