---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: unifi-mcp
  namespace: o11y
spec:
  image: ghcr.io/sirkirby/unifi-network-mcp:0.27.0@sha256:d6603cf82c13357b3b146bd2b1eee467aba068b0cf200c377fe7e58e0498145b
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 3000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  secrets:
    - name: unifi-mcp-secret
      key: UNIFI_API_KEY
      targetEnvName: UNIFI_API_KEY
  env:
    - name: UNIFI_HOST
      value: https://192.168.1.1
    - name: UNIFI_VERIFY_SSL
      value: "false"
  groupRef:
    name: mcp-tools
