---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: victoria-operator
spec:
    chartRef:
        kind: OCIRepository
        name: victoria-metrics-operator
    interval: 1h
    install:
        crds: Skip
    upgrade:
        crds: Skip
        cleanupOnFail: true
    values:
        crds:
            enabled: false
        fullnameOverride: victoria-operator
        operator:
            disable_prometheus_converter: false
            enable_converter_ownership: true
        admissionWebhooks:
            enabled: true
            certManager:
                enabled: true
                issuer:
                    name: selfsigned
                    kind: ClusterIssuer
                    group: cert-manager.io
        serviceMonitor:
            enabled: true
        resources:
            requests:
                cpu: 20m
            limits:
                memory: 512Mi
