---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app line
spec:
  targetNamespace: default
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: storage
    - name: redpanda
      namespace: streaming
    - name: garage
      namespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/default/line/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
