---
# Renovate: docker.io/crowdsecurity/crowdsec
name: crowdsec
services:
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:v1.8.0
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/linux crowdsecurity/sshd crowdsecurity/iptables
      PARSERS: crowdsecurity/geoip-enrich
      GID: "1000"
    volumes:
      - /var/log:/var/log:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - crowdsec-db:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec
      - ./scenarios:/etc/crowdsec/scenarios/custom:ro
      - ./whitelists:/etc/crowdsec/parsers/s02-enrich/custom:ro
      - ./acquis.d:/etc/crowdsec/acquis.d/custom:ro
      - ./config/config.yaml.local:/etc/crowdsec/config.yaml.local:ro
    ports:
      - 127.0.0.1:8088:8080
    healthcheck:
      test:
        - CMD
        - cscli
        - lapi
        - status
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
    networks:
      - default
volumes:
  crowdsec-db:
  crowdsec-config:
networks:
  default:
    name: edge
    external: true
