---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity-secret
    template:
      data:
        CONTINUWUITY_REGISTRATION_TOKEN: "{{ .CONTINUWUITY_REGISTRATION_TOKEN }}"
  dataFrom:
    - extract:
        key: continuwuity
