---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: continuwuity
