---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qui-secret
    template:
      data:
        QUI__OIDC__ENABLED: "true"
        QUI__OIDC__ISSUER: https://id.goyangi.io/
        QUI__OIDC__CLIENT_ID: qui
        QUI__OIDC__REDIRECT_URI: https://qui.goyangi.io/api/auth/oidc/callback
        QUI__OIDC_DISABLE_BUILT_IN_LOGIN: "true"
  dataFrom:
    - extract:
        key: qui
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: qui-session
spec:
  length: 64
  symbols: 0
  allowRepeat: true
  noUpper: false
  secretKeys:
    - SESSION_SECRET
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-session
spec:
  refreshPolicy: CreatedOnce
  target:
    name: qui-session-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        QUI__SESSION_SECRET: "{{ .SESSION_SECRET }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: qui-session
