---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./oidc.yaml
  - ./securitypolicy.yaml
  - ./sonarr-oauth2.yaml
configMapGenerator:
  - name: sonarr-configmap
    files:
      - refresh-series.sh=./resources/refresh-series.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
