---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vgc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vgc-secret
    creationPolicy: Owner
    template:
      data:
        S3_ACCESS_KEY: "{{ .GARAGE_ROOT_USER }}"
        S3_SECRET_KEY: "{{ .GARAGE_ROOT_PASSWORD }}"
        CLOUDFLARE_R2_ACCESS_KEY_ID: "{{ .CLOUDFLARE_R2_ACCESS_KEY_ID }}"
        CLOUDFLARE_R2_SECRET_ACCESS_KEY: "{{ .CLOUDFLARE_R2_SECRET_ACCESS_KEY }}"
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: garage
    - extract:
        key: cloudflare-r2
    - extract:
        key: litellm
