---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./arr-mcp
  - ./flux-operator-mcp
  - ./github-mcp
  - ./grafana-mcp
  - ./ha-mcp
  - ./kubectl-mcp
  - ./kubesearch
  - ./seerr-mcp
  - ./talos-mcp
  - ./unifi-mcp
