---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chisel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chisel-secret
    creationPolicy: Owner
    template:
      data:
        users.json: |
          {
            "{{ .CHISEL_USER }}:{{ .CHISEL_PASS }}": [".*"]
          }
        key.pem: |-
          {{ .CHISEL_KEY }}
  dataFrom:
    - extract:
        key: chisel
