---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chisel
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: chisel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      chisel:
        containers:
          app:
            image:
              repository: jpillora/chisel
              tag: 1.11.5
            args:
              - server
              - --port=8443
              - --reverse
              - --authfile=/config/users.json
              - --keyfile=/config/key.pem
            env:
              TZ: Australia/Sydney
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8443
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8443
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: chisel
        ports:
          tunnel:
            port: 8443
          opencode-work:
            port: 4097
          dev-work:
            port: 4098
    route:
      app:
        hostnames:
          - chisel.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: chisel
                port: 8443
      work-opencode:
        hostnames:
          - work-opencode.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: chisel
                port: 4097
      work-dev:
        hostnames:
          - work-dev.goyangi.io
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  set:
                    - name: Host
                      value: localhost:8080
            backendRefs:
              - name: chisel
                port: 4098
    persistence:
      config:
        type: secret
        name: chisel-secret
        globalMounts:
          - path: /config/users.json
            subPath: users.json
            readOnly: true
          - path: /config/key.pem
            subPath: key.pem
            readOnly: true
