---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: 'true'
    goldilocks.fairwinds.com/vpa-update-mode: Auto
    goldilocks.fairwinds.com/vpa-resource-policy: '{"containerPolicies":[{"containerName":"*","maxAllowed":{"cpu":"250m","memory":"1Gi"}}]}'
  labels:
    goldilocks.fairwinds.com/enabled: 'true'
    resource.kubernetes.io/admin-access: 'true'
