---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set-mono
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.0
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name mono-runner
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-mono
  interval: 1h
  values:
    githubConfigUrl: https://github.com/solanyn/mono
    githubConfigSecret: mono-runner-secret
    minRunners: 0
    maxRunners: 8
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    template:
      spec:
        nodeSelector:
          node-role.kubernetes.io/nodepool: "true"
        tolerations:
          - key: nodepool
            operator: Equal
            value: "true"
            effect: NoSchedule
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.333.1@sha256:1a7726bcaeba4e46fe07fe98e1805b4df78618a71e67758f932862b929f852d4
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RESULTS_URL
                value: http://mono-actions-cache-server.actions-runner-system.svc.cluster.local:3000/
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
            resources:
              requests:
                cpu: "2"
                memory: 4Gi
              limits:
                cpu: "6"
                memory: 12Gi
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        volumes:
          - name: work
            emptyDir: {}
