---
http:
  routers:
    garage-s3:
      entryPoints:
        - websecure
      rule: Host(`s3.goyangi.io`)
      service: garage-s3
      tls:
        certResolver: cf
    garage-admin:
      entryPoints:
        - websecure
      rule: Host(`garage-admin.goyangi.io`)
      service: garage-admin
      tls:
        certResolver: cf
    truenas:
      entryPoints:
        - websecure
      rule: Host(`nas.goyangi.io`)
      service: truenas
      tls:
        certResolver: cf
  services:
    garage-admin:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3903
    garage-s3:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3900
    truenas:
      loadBalancer:
        servers:
          - url: https://host.docker.internal:10443
        serversTransport: insecure
  serversTransports:
    insecure:
      insecureSkipVerify: true
