---
http:
  routers:
    garage-s3:
      entryPoints:
        - websecure
      rule: Host(`s3.goyangi.io`)
      service: garage-s3
      tls:
        certResolver: cf
    garage-admin:
      entryPoints:
        - websecure
      rule: Host(`garage-admin.goyangi.io`)
      service: garage-admin
      tls:
        certResolver: cf
    truenas:
      entryPoints:
        - websecure
      rule: Host(`nas.goyangi.io`)
      service: truenas
      tls:
        certResolver: cf
  services:
    garage-admin:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3903
    garage-s3:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3900
    truenas:
      loadBalancer:
        servers:
          - url: https://host.docker.internal:10443
        serversTransport: insecure
    versitygw-s3:
      entryPoints:
        - websecure
      rule: Host(`s3-versitygw.goyangi.io`)
      service: versitygw-s3
      tls:
        certResolver: cf
    versitygw-admin:
      entryPoints:
        - websecure
      rule: Host(`versitygw-admin.goyangi.io`)
      service: versitygw-admin
      tls:
        certResolver: cf
    versitygw-webui:
      entryPoints:
        - websecure
      rule: Host(`versitygw.goyangi.io`)
      service: versitygw-webui
      tls:
        certResolver: cf
  services:
    versitygw-admin:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3911
    versitygw-s3:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3910
    versitygw-webui:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3912
  serversTransports:
    insecure:
      insecureSkipVerify: true
