---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bindery
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: miroir-replicated
