---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-sa-token
spec:
  secretStoreRef:
    kind: SecretStore
    name: o11y-secrets
  target:
    name: grafana-sa-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: grafana-sa-token
        property: token
