---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana-mcp
  namespace: ai
spec:
  image: grafana/mcp-grafana:1.6.1@sha256:f49a704a44c193894381f535646b0fca060238c678e8dc22d16f5e2174c5cef5
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - --transport
            - streamable-http
            - --allowed-hosts
            - "*"
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.o11y.svc:3000
  secrets:
    - name: grafana-sa-token
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  groupRef:
    name: mcp-tools
