---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana-mcp
  namespace: ai
spec:
  image: grafana/mcp-grafana:2.0.2@sha256:78d208116ec52b09b44f0eca66892073b39aefcb64483c54d43255c8eab7e97a
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - --transport
            - streamable-http
            - --allowed-hosts
            - "*"
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.o11y.svc:3000
  secrets:
    - name: grafana-sa-token
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  groupRef:
    name: mcp-tools
