---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: truenas
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        name: truenas-secret
        creationPolicy: Owner
        template:
            type: Opaque
            data:
                truenas_ssh_private_key: "{{ .TRUENAS_SSH_PRIVATE_KEY }}"
                truenas_ssh_host_key_fingerprint: "{{ .TRUENAS_SSH_HOST_KEY_FINGERPRINT }}"
                onepassword_credentials_json: "{{ .OP_CREDENTIALS_JSON }}"
                onepassword_connect_token: "{{ .OP_CONNECT_TOKEN }}"
                truenas_api_key: "{{ .TRUENAS_API_KEY }}"
                doco_cd_webhook_secret: "{{ .DOCO_CD_WEBHOOK_SECRET }}"
    dataFrom:
        - extract:
              key: truenas
        - extract:
              key: 1password
