---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustical
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rustical-secret
    creationPolicy: Owner
    template:
      data:
        config.toml: |
          [http]
          listen = "0.0.0.0:5232"

          [auth]
          type = "basic"

          [[auth.accounts]]
          username = "andrew@goyangi.io"
          password = "{{ .BAIKAL_ADMIN_PASSWORD }}"

          [data]
          type = "sqlite"
          path = "/data/rustical.db"
  dataFrom:
    - extract:
        key: baikal
