---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustical
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rustical-secret
    creationPolicy: Owner
    template:
      data:
        RUSTICAL_OIDC__CLIENT_SECRET: "{{ .RUSTICAL_OIDC_CLIENT_SECRET }}"
        RUSTICAL_DATA_STORE__SQLITE__DB_URL: sqlite:///var/lib/rustical/rustical.db
  dataFrom:
    - extract:
        key: rustical
