---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
    name: goyangi
spec:
    configSelector:
        matchLabels:
            app.kubernetes.io/instance: goyangi
    disableNamespaceMatcher: true
    storage:
        volumeClaimTemplate:
            spec:
                storageClassName: miroir-replicated
                resources:
                    requests:
                        storage: 1Gi
