---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ${CONTROLLER:=Deployment}
    name: ${APP}
  minReplicas: 0
  maxReplicas: 1
  metrics:
    - type: External
      external:
        metric:
          name: probe_success
          selector:
            matchLabels:
              job: probe/o11y/nfs
        target:
          type: Value
          value: "1"
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0
