---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kanidm-admin-passwords
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: kanidm-admin-password-source
  template:
    data:
      ADMIN_USERNAME: YWRtaW4=
      ADMIN_PASSWORD: '{{ index . "ADMIN_PASSWORD" | b64enc }}'
      IDM_ADMIN_USERNAME: aWRtX2FkbWlu
      IDM_ADMIN_PASSWORD: '{{ index . "IDM_ADMIN_PASSWORD" | b64enc }}'
  data:
    - match:
        secretKey: ADMIN_PASSWORD
        remoteRef:
          remoteKey: kanidm-admin-passwords
          property: ADMIN_PASSWORD
    - match:
        secretKey: IDM_ADMIN_PASSWORD
        remoteRef:
          remoteKey: kanidm-admin-passwords
          property: IDM_ADMIN_PASSWORD
