---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-admin-password-source
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kanidm-admin-password-source
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: kanidm-admin-passwords
        property: ADMIN_PASSWORD
    - secretKey: IDM_ADMIN_PASSWORD
      remoteRef:
        key: kanidm-admin-passwords
        property: IDM_ADMIN_PASSWORD
