apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: andrew
  namespace: security
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: Andrew
    mail:
      - andrew@goyangi.io
  credentialsTokenTtl: 3600

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: sonarr-users
  namespace: security
spec:
  kanidmRef:
    name: kanidm
  members:
    - andrew
