---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: sonarr
  namespace: security
spec:
  kanidmRef:
    name: kanidm
  displayname: Sonarr
  origin: https://sonarr.goyangi.io
  redirectUrl:
    - https://sonarr.goyangi.io/oauth2/callback
  public: false
  scopeMap:
    - group: sonarr-users
      scopes:
        - openid
        - profile
        - email
        - groups
  strictRedirectUrl: true
  secretKeyAliases:
    clientSecret:
      - client-secret
