---
apiVersion: home-ops.io/v1alpha1
kind: XComputeNodePool
metadata:
  name: nodepool
spec:
  region: australia-southeast1
  machineType: e2-medium
  spot: true
  diskSizeGb: 200
  diskType: pd-standard
  image: projects/${GCP_PROJECT_ID}/global/images/talos-tailscale-v1-12-6
  machineToken: ${MACHINE_TOKEN}
  machineCaCrt: ${MACHINE_CA_CRT}
  clusterToken: ${CLUSTER_TOKEN}
  clusterCaCrt: ${CLUSTER_CA_CRT}
  clusterId: ${CLUSTER_ID}
  clusterSecret: ${CLUSTER_SECRET}
  tailscaleAuthKey: ${TAILSCALE_AUTHKEY}
  targetSize: 0
  maxSize: 8
