---
apiVersion: home-ops.io/v1alpha1
kind: XComputeNodePool
metadata:
  name: nodepool
spec:
  targetSize: 0
  region: australia-southeast1
  machineType: e2-standard-8
  spot: true
  diskSizeGb: 200
  diskType: pd-standard
  # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
  # talos-version: v1.13.2
  image: projects/${GCP_PROJECT_ID}/global/images/talos-tailscale-v1-13-2
  machineToken: ${MACHINE_TOKEN}
  machineCaCrt: ${MACHINE_CA_CRT}
  clusterToken: ${CLUSTER_TOKEN}
  clusterCaCrt: ${CLUSTER_CA_CRT}
  clusterId: ${CLUSTER_ID}
  clusterSecret: ${CLUSTER_SECRET}
  tailscaleClientSecret: ${TAILSCALE_CLIENT_SECRET}
  maxSize: 8
