---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      annotationSelector: "!anubis.home/skip-route-patch"
    patch: |-
      - op: add
        path: /spec/values/route/app/rules
        value:
          - backendRefs:
              - name: ${APP}-anubis
                port: 8080
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  set:
                    - name: X-Real-Ip
                      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
            timeouts:
              request: 300s
