---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: livekit
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: livekit
  values:
    controllers:
      livekit:
        containers:
          app:
            image:
              repository: livekit/livekit-server
              tag: v1.8.4
            args:
              - --config
              - /etc/livekit/config.yaml
            envFrom:
              - secretRef:
                  name: livekit-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 7880
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 7880
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.69.137,fd5d:a293:f321:69::137
          external-dns.alpha.kubernetes.io/hostname: livekit.goyangi.io
        externalTrafficPolicy: Local
        controller: livekit
        ports:
          http:
            port: 7880
            protocol: TCP
          rtc-tcp:
            port: 7881
            protocol: TCP
          turn-udp:
            port: 3478
            protocol: UDP
    persistence:
      config:
        type: configMap
        name: livekit-config
        globalMounts:
          - path: /etc/livekit/config.yaml
            subPath: config.yaml
    configMaps:
      config:
        data:
          config.yaml: |
            port: 7880
            rtc:
              tcp_port: 7881
              port_range_start: 50000
              port_range_end: 50060
              use_external_ip: false
            turn:
              enabled: true
              domain: livekit.goyangi.io
              tls_port: 0
              udp_port: 3478
            keys: {}
            logging:
              level: info
