---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - httproute.yaml
  - lk-jwt-helmrelease.yaml
  - lk-jwt-httproute.yaml
  - ocirepository.yaml
  - lk-jwt-ocirepository.yaml
