---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentgateway-apikey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: agentgateway-apikey
    creationPolicy: Owner
    template:
      data:
        openclaw: "{{ .AGENTGATEWAY_OPENCLAW_API_KEY }}"
        personal: "{{ .AGENTGATEWAY_PERSONAL_API_KEY }}"
        work: "{{ .AGENTGATEWAY_WORK_API_KEY }}"
        gha: "{{ .AGENTGATEWAY_GHA_API_KEY }}"
  dataFrom:
    - extract:
        key: agentgateway

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minimax-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minimax-auth
    creationPolicy: Owner
    template:
      data:
        Authorization: "Bearer {{ .MINIMAX_API_KEY }}"
  dataFrom:
    - extract:
        key: minimax

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deepseek-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: deepseek-auth
    creationPolicy: Owner
    template:
      data:
        Authorization: "Bearer {{ .DEEPSEEK_API_KEY }}"
  dataFrom:
    - extract:
        key: deepseek
