---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: katib-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: katib-postgres-secrets
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .KATIB_DB_USER }}"
        POSTGRES_PASSWORD: "{{ .KATIB_DB_PASSWORD }}"
        POSTGRES_DB: katib
  data:
    - secretKey: KATIB_DB_USER
      remoteRef:
        key: kubeflow-katib
        property: DB_USER
    - secretKey: KATIB_DB_PASSWORD
      remoteRef:
        key: kubeflow-katib
        property: DB_PASSWORD
