---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-mysql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mysql-secret
    creationPolicy: Owner
    template:
      data:
        username: "{{ .KFP_DB_USER }}"
        password: "{{ .KFP_DB_PASSWORD }}"
  data:
    - secretKey: KFP_DB_USER
      remoteRef:
        key: kubeflow-pipelines
        property: DB_USER
    - secretKey: KFP_DB_PASSWORD
      remoteRef:
        key: kubeflow-pipelines
        property: DB_PASSWORD
