---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mlpipeline-minio-secret
    creationPolicy: Owner
    template:
      data:
        accesskey: "{{ .GARAGE_ROOT_USER }}"
        secretkey: "{{ .GARAGE_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: garage
