---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volsync-metrics
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: volsync-perfectra1n
  endpoints:
    - port: https
      path: /metrics
      scheme: http
      interval: 30s
