---
- id: github
  execute-command: /config/github.sh
  command-working-directory: /tmp
  pass-body-to-command: true
  pass-environment-to-command:
    - envname: OPENCLAW_HOOKS_TOKEN
      source: string
      name: '{{ getenv "OPENCLAW_HOOKS_TOKEN" }}'
  pass-arguments-to-command:
    - source: header
      name: X-GitHub-Event
  trigger-rule:
    match:
      type: payload-hmac-sha256
      secret: '{{ getenv "GITHUB_WEBHOOK_SECRET" }}'
      parameter:
        source: header
        name: X-Hub-Signature-256
- id: 'opencode-{{ getenv "OPENCODE_WEBHOOK_TOKEN" }}'
  execute-command: /config/opencode.sh
  command-working-directory: /tmp
  pass-body-to-command: true
  pass-environment-to-command:
    - envname: OPENCLAW_HOOKS_TOKEN
      source: string
      name: '{{ getenv "OPENCLAW_HOOKS_TOKEN" }}'
