---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: opencode-sse
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: opencode
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: opencode-personal
  timeout:
    http:
      maxStreamDuration: "0s"
      connectionIdleTimeout: "1h"
