---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opencode-secret
    creationPolicy: Owner
    template:
      data:
        OPENAI_API_KEY: "{{ .AGENTGATEWAY_API_KEY }}"
        GITHUB_USERNAME: solanyn
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        FORGEJO_USERNAME: andrew
        FORGEJO_TOKEN: "{{ .FORGEJO_TOKEN }}"
  dataFrom:
    - extract:
        key: opencode
    - extract:
        key: agentgateway
    - extract:
        key: github
    - extract:
        key: forgejo
