---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubesearch
  namespace: ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: miroir-local
