---
services:
  versitygw:
    image: ghcr.io/versity/versitygw:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    environment:
      ROOT_ACCESS_KEY: ${VERSITYGW_ROOT_ACCESS_KEY}
      ROOT_SECRET_KEY: ${VERSITYGW_ROOT_SECRET_KEY}
      VGW_PORT: ":9000"
      VGW_IAM_DIR: /mnt/iam
      VGW_VERSIONING_DIR: /mnt/versioning
      VGW_BACKEND: posix
      VGW_BACKEND_ARGS: /mnt/data
      VGW_ADMIN_PORT: ":9001"
      VGW_WEBUI_PORT: ":9002"
      VGW_WEBUI_GATEWAYS: "http://nas.internal:9000"
      VGW_WEBUI_ADMIN_GATEWAYS: "http://nas.internal:9001"
      TZ: Australia/Sydney
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - /mnt/world/versitygw/data:/mnt/data
      - /mnt/world/versitygw/iam:/mnt/iam
      - /mnt/world/versitygw/versioning:/mnt/versioning
