---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: honcho
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        name: honcho-secret
        creationPolicy: Owner
        template:
            data:
                HONCHO_POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
                HONCHO_POSTGRES_DBNAME: honcho
                HONCHO_POSTGRES_USER: "{{ .HONCHO_POSTGRES_USER }}"
                HONCHO_POSTGRES_PASS: "{{ .HONCHO_POSTGRES_PASSWORD }}"
                INIT_POSTGRES_HOST: &dbHost postgres-rw.storage.svc.cluster.local
                INIT_POSTGRES_DBNAME: &dbName honcho
                INIT_POSTGRES_USER: &dbUser "{{ .HONCHO_POSTGRES_USER }}"
                INIT_POSTGRES_PASS: &dbPass "{{ .HONCHO_POSTGRES_PASSWORD }}"
                INIT_POSTGRES_SUPER_USER: postgres
                INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
                MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
    dataFrom:
        - extract:
              key: honcho
        - extract:
              key: cloudnative-pg
        - extract:
              key: minimax
