---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honcho
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: honcho-secret
    creationPolicy: Owner
    template:
      data:
        DB_CONNECTION_URI: "postgresql+psycopg://{{ .HONCHO_POSTGRES_USER }}:{{ .HONCHO_POSTGRES_PASSWORD }}@postgres-rw.storage.svc.cluster.local/honcho"
        INIT_POSTGRES_HOST: &dbHost postgres-rw.storage.svc.cluster.local
        INIT_POSTGRES_DBNAME: &dbName honcho
        INIT_POSTGRES_USER: &dbUser "{{ .HONCHO_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .HONCHO_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        OPENAI_API_KEY: "{{ .HONCHO_API_KEY }}"
  dataFrom:
    - extract:
        key: honcho
    - extract:
        key: cloudnative-pg
