---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: models
spec:
  parentRefs:
    - name: ai
      namespace: network
  rules:
    - matches:
        - path:
            type: Exact
            value: /v1/models
      backendRefs:
        - name: agentgateway-models
          group: agentgateway.dev
          kind: AgentgatewayBackend
