---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: models-passthrough
spec:
  targetRefs:
    - kind: HTTPRoute
      name: models
      group: gateway.networking.k8s.io
  backend:
    ai:
      routes:
        "/v1/models": Passthrough
        "*": Passthrough
